import AppKit
import CryptoKit
import Combine

struct Clip: Identifiable {
    enum Content { case text(String), image(Data, NSPasteboard.PasteboardType) }
    let id = UUID()
    let date = Date()
    let content: Content
    let fingerprint: String
    let byteCount: Int

    var text: String? {
        if case .text(let text) = content { return text }
        return nil
    }
    var image: NSImage? {
        if case .image(let data, _) = content { return NSImage(data: data) }
        return nil
    }
    var title: String { text?.replacingOccurrences(of: "\n", with: " ") ?? "Изображение" }
}

@MainActor
final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [Clip] = []
    @Published var isPaused = false {
        didSet { lastChange = board.changeCount }
    }
    @Published private(set) var accessDenied = false
    @Published private(set) var needsConsent = false
    private let board: NSPasteboard
    private var lastChange: Int
    private var timer: Timer?
    private var requestedChange: Int?
    let itemLimit: Int
    let memoryLimit: Int
    static let maxItemBytes = 12 * 1024 * 1024
    static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
        "com.typeit4me.clipping"
    ]

    init(board: NSPasteboard = .general, itemLimit: Int = 40, memoryLimit: Int = 48 * 1024 * 1024) {
        self.board = board
        self.lastChange = board.changeCount
        self.itemLimit = itemLimit
        self.memoryLimit = memoryLimit
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.8, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        timer?.tolerance = 0.2
    }

    func poll(userInitiated: Bool = false) {
        let change = board.changeCount
        guard !isPaused else { lastChange = change; return }
        guard change != lastChange || userInitiated else { return }
        if #available(macOS 15.4, *), board.name == .general {
            accessDenied = board.accessBehavior == .alwaysDeny
            if accessDenied { needsConsent = false; return }
            // Never trigger repeated background permission alerts.
            if board.accessBehavior == .ask && !userInitiated {
                needsConsent = true
                return
            }
        }
        guard requestedChange != change || userInitiated else { return }
        requestedChange = change
        lastChange = change
        needsConsent = false
        guard let types = board.types,
              Self.privateTypes.isDisjoint(with: types.map(\.rawValue)) else { return }
        for type in [NSPasteboard.PasteboardType.png, .tiff] where types.contains(type) {
            if let data = board.data(forType: type), data.count <= Self.maxItemBytes,
               NSImage(data: data) != nil {
                append(.image(data, type), data: data, prefix: "image:")
                return
            }
        }
        if let text = board.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let data = Data(text.utf8)
            guard data.count <= Self.maxItemBytes else { return }
            append(.text(text), data: data, prefix: "text:")
        }
    }

    private func append(_ content: Clip.Content, data: Data, prefix: String) {
        let fingerprint = prefix + SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
        items.removeAll { $0.fingerprint == fingerprint }
        items.insert(Clip(content: content, fingerprint: fingerprint, byteCount: data.count), at: 0)
        var bytes = 0
        items = Array(items.prefix(itemLimit).prefix { clip in
            bytes += clip.byteCount
            return bytes <= memoryLimit
        })
    }

    @discardableResult
    func copy(_ item: Clip) -> Bool {
        board.clearContents()
        let success: Bool
        switch item.content {
        case .text(let text): success = board.setString(text, forType: .string)
        case .image(let data, let type): success = board.setData(data, forType: type)
        }
        lastChange = board.changeCount
        return success
    }

    func remove(_ item: Clip) { items.removeAll { $0.id == item.id } }
    func clear() { items.removeAll() }
}
